title = "Marta Arpa Coaching et Conseil"

[params]
description = "Coaching exécutif et personnel, conseil en changement et gestion de projets. J'accompagne vers une transformation à impact réel et durable."
images = ['images/metaimage.jpg']
show_post_dates = false

[languages]
[languages.fr]
languageName = "Français"
weight = 2
[languages.es]
languageName = "Espagnol"
weight = 3
[languages.ca]
languageCode = "ca"
languageName = "Catalan"
weight = 4

[params.footer]
[[params.footer.links]]
header = "À propos de moi"
[[params.footer.links.links]]
title = "À propos de moi"
url = "/fr/about/main/"

[[params.footer.links]]
header = "Services"
[[params.footer.links.links]]
title = "Coaching Éxécutif"
url = "/fr/services/coaching-ex/main/"
[[params.footer.links.links]]
title = "Coaching Personnel"
url = "/fr/services/coaching-per/main/"
[[params.footer.links.links]]
title = "PMaaS et CMaaS"
url = "/fr/services/maas/main/"
[[params.footer.links.links]]
title = "Conseil"
url = "/fr/services/consultancy/main/"

[[params.footer.links]]
header = "Contact"
[[params.footer.links.links]]
title = "Newsletter"
url = "/fr/newsletter/main/"
[[params.footer.links.links]]
title = "Séance gratuite"
url = "https://meet.brevo.com/marta-arpa/sesion-gratuita-"
[[params.footer.links.links]]
title = "Envoyez un message"
url = "/fr/contact/main/"

[params.footer.contact_form]
enabled = true
header = "Parlons-en"
action = "https://forms.un-static.com/forms/aa737dbb5a6d63dfca1ca4784b9b1cffcac83569"
