title = "Marta Arpa Coaching i Consultoria"
[params]
description = "Coaching executiu i personal, consultoria del canvi i gestió de projectes. Acompanyo persones i organitzacions cap a una transformació amb impacte real i durador."
images = ['images/metaimage.jpg']
show_post_dates = false

[languages]
[languages.fr]
languageName = "Français"
weight = 2
[languages.es]
languageName = "Espagnol"
weight = 3
[languages.cat]
languageCode = "ca"
languageName = "Català"
weight = 4

[params.footer]
[[params.footer.links]]
header = "Sobre mi"
[[params.footer.links.links]]
title = "Sobre mi"
url = "/cat/about/main/"

[[params.footer.links]]
header = "Serveis"
[[params.footer.links.links]]
title = "Coaching Executiu"
url = "/cat/services/coaching-ex/main/"
[[params.footer.links.links]]
title = "Coaching Personal"
url = "/cat/services/coaching-per/main/"
[[params.footer.links.links]]
title = "PMaaS i CMaaS"
url = "/cat/services/maas/main/"
[[params.footer.links.links]]
title = "Consultoria"
url = "/cat/services/consultancy/main/"

[[params.footer.links]]
header = "Contacte"
[[params.footer.links.links]]
title = "Newsletter"
url = "/cat/newsletter/main/"
[[params.footer.links.links]]
title = "Sessió gratuïta"
url = "https://meet.brevo.com/marta-arpa/sesion-gratuita-"
[[params.footer.links.links]]
title = "Envia'm un missatge"
url = "/cat/contact/main/"

[params.footer.contact_form]
enabled = true
header = "Parlem-ne"
action = "https://forms.un-static.com/forms/a5e0b809ad97bad3c283c284912e65d715500500"
