title = "Marta Arpa Coaching & Consultancy"

[params]
description = "A business/corporate style responsive site template."
images = ['images/metaimage.jpg']
show_post_dates = false

[languages]
[languages.en]
languageName = "English"
weight = 1
[languages.fr]
languageName = "Fran√ßais"
weight = 2
[languages.es]
languageName = "Espagnol"
weight = 3
[languages.cat]
languageCode = "ca"
languageName = "Catalan"
weight = 4

[params.footer]
[[params.footer.links]]
header = "About me"
[[params.footer.links.links]]
title = "About me"
url = "/en/about/main/"

[[params.footer.links]]
header = "Services"
[[params.footer.links.links]]
title = "Executive coaching"
url = "/en/services/coaching-ex/main/"
[[params.footer.links.links]]
title = "Personal Coaching "
url = "/en/services/coaching-per/main/"
[[params.footer.links.links]]
title = "PMaaS and CMaaS"
url = "/en/services/maas/main/"
[[params.footer.links.links]]
title = "Consulting"
url = "/en/services/consultancy/main/"

[[params.footer.links]]
header = "Contact"
[[params.footer.links.links]]
title = "Newsletter"
url = "/en/newsletter/main/"
[[params.footer.links.links]]
title = "Free session"
url = "https://meet.brevo.com/marta-arpa/sesion-gratuita-"
[[params.footer.links.links]]
title = "Send me a message"
url = "/en/contact/main/"

[params.footer.contact_form]
enabled = true
header = "Let's talk"
action = "https://forms.un-static.com/forms/a9ce19c95290561fd95c7ccab9104c6510aed4c4"
