baseURL = "https://martaarpa.com"
#canonifyURLs = true
languageCode = "en-us"
copyright = "© Marta Arpa. All rights reserved"
title = "Marta Arpa Coaching y Consultoría"
defaultContentLanguage = "es"

[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files

[outputs]
home = ["HTML", "RSS", "ROBOTS"]

[languages]
[languages.en]
languageName = "Inglés"
weight = 1
[languages.fr]
languageName = "Francés"
weight = 2
[languages.es]
languageName = "Español"
weight = 3
[languages.ca]
languageCode = "ca"
languageName = "Catalán"
weight = 4


[params]
description = "Coaching ejecutivo y personal, consultoría del cambio y gestión de proyectos. Acompaño a personas y organizaciones hacia un impacto real."
images = ['images/metaimage.jpg']
show_post_dates = false
recaptchaSiteKey = "6Ld-08orAAAAANupWBL2u9QZu78ZB3O4E4-R65a6"

[params.footer]
[[params.footer.links]]
header = "Acerca de mí"
[[params.footer.links.links]]
title = "Acerca de mí"
url = "/about/main/"

[[params.footer.links]]
header = "Mis Servicios"
[[params.footer.links.links]]
title = "Coaching Ejecutivo"
url = "/services/coaching-ex/main/"
[[params.footer.links.links]]
title = "Coaching Personal"
url = "/services/coaching-per/main/"
[[params.footer.links.links]]
title = "PMaaS y CMaaS"
url = "/services/maas/main/"
[[params.footer.links.links]]
title = "Consultoría"
url = "/services/consultancy/main/"

[[params.footer.links]]
header = "Contacto"
[[params.footer.links.links]]
title = "Newsletter"
url = "/newsletter/main/"
[[params.footer.links.links]]
title = "Sesión gratuita"
url = "https://meet.brevo.com/marta-arpa/sesion-gratuita-"
[[params.footer.links.links]]
title = "Envíame un mensaje"
url = "/contact/main/"


[params.footer.contact_form]
enabled = true
header = "Hablemos"
action = "https://forms.un-static.com/forms/4558fb21fb022b78fb17ba7616be6bc4e0c70a4a"


[[params.social]]
title = "LinkedIn"
icon = "fa-linkedin-in"
url = "https://www.linkedin.com/in/marta-arpa-moragrega/"

[[params.social]]
title = "Instagram"
icon = "fa-instagram"
url = "https://www.instagram.com/marta_arpa_coaching"

[server]
[[server.headers]]
for = "/**"
[server.headers.values]
Content-Security-Policy = "default-src 'self'; frame-src 'self' https://*.brevo.com https://*.sendinblue.com https://*.sibforms.com https://www.google.com https://www.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.brevo.com https://*.sendinblue.com https://*.sibforms.com https://www.google.com https://www.gstatic.com https://www.googletagmanager.com https://cloud.umami.is; connect-src 'self' https://www.google.com https://www.gstatic.com https://www.google-analytics.com https://analytics.google.com https://cloud.umami.is; style-src 'self' 'unsafe-inline' https://*.brevo.com https://*.sendinblue.com https://*.sibforms.com; style-src-attr 'unsafe-inline'"
