[[main]]
name = "Services"
weight = 30
[[main]]
parent = "Services"
name = "Executive Coaching"
url = '/en/services/coaching-ex/main/'
weight = 31
[[main]]
parent = "Services"
name = "Personal Coaching"
url = '/en/services/coaching-per/main/'
weight = 32
[[main]]
parent = "Services"
name = "PMaaS and CMaaS"
url = '/en/services/maas/main/'
weight = 33
[[main]]
parent = "Services"
name = "Consulting"
url = '/en/services/consultancy/main/'
weight = 34
